
version: 2.1
default: &default
  working_directory: ~/repo
  docker:
    - image: circleci/node:latest-browsers
  environment:
    HUGO_BUILD_DIR: ~/hugo/public
commands:
  prepare:
    description: "Prepare working directory"
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run: 
          name: install hugo
          command: | 
            wget https://github.com/gohugoio/hugo/releases/download/v0.78.1/hugo_0.78.1_Linux-64bit.deb
            sudo dpkg -i hugo_0.78.1_Linux-64bit.deb
jobs:
  build:
    <<: *default
    steps:
      - prepare
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
  deploy:
    <<: *default
    steps:
      - prepare
      - run: |
          git clone $CIRCLE_REPOSITORY_URL out
          cd out
          git checkout gh-pages || git checkout --orphan gh-pages
          git rm -rf .
          cd ..
          hugo
          cp -a public/. out/.
          mkdir -p out/.circleci && cp -a .circleci/. out/.circleci/.
          cd out
          git config user.name "CircleCI"
          git config user.email "circle@circleci"
          git add -A
          git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1} [ci skip]" --allow-empty
          git push origin gh-pages
workflows:
  version: 2.1
  build-flow:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
                - gh-pages
      - deploy:
          filters:
            branches:
              only: master